openapi: 3.1.0
info:
  title: GPT Google Sheets Proxy
  version: 1.0.0
servers:
  - url: https://gpt-google-sheets-proxy-7glv.onrender.com
paths:
  /sheets/{spreadsheetId}:
    get:
      operationId: getSheet
      summary: Read data from a Google Sheet
      description: Get values from a specific sheet and optional range
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
        - name: range
          in: query
          required: false
          description: The A1 notation of the range to retrieve, e.g. "Sheet1!A1:B5"
          schema:
            type: string
      responses:
        '200':
          description: Successful response with sheet data
    post:
      operationId: appendSheetData
      summary: Append data to a Google Sheet
      description: Append rows to the specified sheet and optional range
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                range:
                  type: string
                  description: A1 range where to insert data (e.g. "Sheet1!A1")
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
              required:
                - values
      responses:
        '200':
          description: Data appended successfully
  /sheets:
    post:
      operationId: createSpreadsheet
      summary: Create a new Google Spreadsheet
      description: Creates a new spreadsheet with the optional given title
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the new spreadsheet
      responses:
        '200':
          description: Spreadsheet created successfully
