openapi: 3.1.0
info:
  title: GPT Sheets Proxy
  version: 1.0.0
servers:
  - url: https://gpt-google-sheets-proxy-7glv.onrender.com
paths:
  /sheets:
    post:
      summary: Создать новую таблицу
      operationId: createSheet
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        '200':
          description: Успешное создание таблицы

  /sheets/{spreadsheetId}:
    get:
      summary: Получить данные из таблицы
      operationId: getSheetValues
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
        - name: range
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Данные получены
    post:
      summary: Добавить строки в таблицу
      operationId: appendData
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                range:
                  type: string
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        '200':
          description: Строки добавлены

  /sheets/{spreadsheetId}/update:
    post:
      summary: Обновить диапазон (перезапись)
      operationId: updateValues
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                range:
                  type: string
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        '200':
          description: Диапазон обновлён

  /sheets/{spreadsheetId}/batchUpdate:
    post:
      summary: Выполнить batchUpdate (структура, стили, формат)
      operationId: batchUpdate
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                requests:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: BatchUpdate выполнен

  /sheets/{spreadsheetId}/structure:
    get:
      summary: Получить структуру таблицы (листы, ID)
      operationId: getStructure
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Структура получена
