openapi: 3.1.0
info:
  title: GPT Google Sheets Proxy
  version: 1.0.0
servers:
  - url: https://gpt-google-sheets-proxy-7glv.onrender.com

paths:
  /sheets:
    post:
      summary: Создать новую таблицу
      operationId: createSheet
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        "200":
          description: Таблица создана

  /sheets/{spreadsheetId}:
    get:
      summary: Получить данные из таблицы
      operationId: getSheetValues
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
        - name: range
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Данные получены

    post:
      summary: Добавить строки в таблицу
      operationId: appendRows
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                range:
                  type: string
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        "200":
          description: Данные добавлены

  /sheets/{spreadsheetId}/structure:
    get:
      summary: Получить структуру таблицы (названия листов, ID)
      operationId: getSheetStructure
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Структура получена

  /sheets/{spreadsheetId}/update:
    post:
      summary: Перезаписать данные в диапазоне
      operationId: updateRange
      parameters:
        - name: spreadsheetId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                range:
                  type: string
                values:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
      responses:
        "200":
          description: Данные обновлены

  /batchUpdate:
    post:
      summary: Выполнить batchUpdate (формулы, стили, сортировка, фильтры и др.)
      operationId: batchUpdate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - spreadsheetId
                - requestBody
              properties:
                spreadsheetId:
                  type: string
                requestBody:
                  type: object
                  required:
                    - requests
                  properties:
                    requests:
                      type: array
                      description: Массив команд Google Sheets API
                      items:
                        type: object
      responses:
        "200":
          description: BatchUpdate выполнен
        "400":
          description: Ошибка в параметрах запроса

  /insertFormulaColumn:
    post:
      summary: Вставить колонку с формулами
      operationId: insertFormulaColumn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - spreadsheetId
                - formulas
                - startRow
                - columnIndex
              properties:
                spreadsheetId:
                  type: string
                formulas:
                  type: array
                  description: Формулы и заголовок (в виде строк, например "=A2+1")
                  items:
                    type: string
                startRow:
                  type: integer
                  description: Индекс начальной строки (нумерация с 0)
                columnIndex:
                  type: integer
                  description: Индекс колонки (A=0, B=1 и т.д.)
      responses:
        "200":
          description: Формулы вставлены
